const getUser=()=>JSON.parse(localStorage.getItem('resumeBuilderUser')||'null');
const getResume=()=>JSON.parse(localStorage.getItem('resumeData')||'null');
const requireLogin=()=>{if(localStorage.getItem('loggedIn')!=='true'){location.href='login.html';return false}return true};
function logout(){localStorage.removeItem('loggedIn');location.href='index.html'}
function showUser(){const u=getUser();document.querySelectorAll('[data-user]').forEach(x=>x.textContent=u?.name||'Mahesh')}
function registerHandler(e){e.preventDefault();const name=nameEl.value.trim(),email=regEmail.value.trim(),password=regPassword.value,confirm=confirmPassword.value;if(password!==confirm)return alert('Passwords do not match.');if(password.length<6)return alert('Password must contain at least 6 characters.');localStorage.setItem('resumeBuilderUser',JSON.stringify({name,email,password}));alert('Registration successful!');location.href='login.html'}
function loginHandler(e){e.preventDefault();const u=getUser();if(!u)return alert('Please register first.');if(loginEmail.value.trim()===u.email&&loginPassword.value===u.password){localStorage.setItem('loggedIn','true');localStorage.setItem('loggedInEmail',u.email);alert('Login successful!');location.href='dashboard.html'}else alert('Invalid email or password.')}
function saveResume(e){e.preventDefault();const data={name:rName.value.trim(),email:rEmail.value.trim(),phone:rPhone.value.trim(),address:rAddress.value.trim(),profile:rProfile.value.trim(),education:rEducation.value.trim(),skills:rSkills.value.trim(),projects:rProjects.value.trim(),experience:rExperience.value.trim(),certifications:rCertifications.value.trim()};const file=photo.files[0];if(file){const reader=new FileReader();reader.onload=()=>{data.photo=reader.result;localStorage.setItem('resumeData',JSON.stringify(data));location.href='resume.html'};reader.readAsDataURL(file)}else{localStorage.setItem('resumeData',JSON.stringify(data));location.href='resume.html'}}
function loadForm(){const d=getResume();if(!d)return;Object.entries(d).forEach(([k,v])=>{const el=document.getElementById(k);if(el&&k!=='photo')el.value=v||''})}
function loadResume(){const d=getResume();if(!d){alert('Create a resume first.');location.href='resume-form.html';return}Object.entries(d).forEach(([k,v])=>{const el=document.getElementById('view-'+k);if(el)el.textContent=v||'—';const head=document.getElementById('view-'+k+'-head');if(head)head.textContent=v||''});if(d.photo)document.getElementById('view-photo').src=d.photo}
function printResume(){window.print()}
